### ISSUE TITLE
Create Tag UI Component

### ISSUE THREAD

**Issue by lilycoco** [rokumura7/penguinhouse_front#6]
Create Tag UI Component with storybook

**Comment by rokumura7** [comment]
I'm sorry, but what do you mean "Tag"?
Is it something like labels on GitHub?
Or, I can choose any kinds of tags like anchor link tag, list tag or others that I want?

**Comment by lilycoco** [comment]
Ah, sorry I meant like this. 
https://vuetifyjs.com/en/components/chips/

In my company, call it`Tag` so 😇
If you like, you can change the component name `Label` or others.

You can add any kinds of props you want too 😎

**Comment by rokumura7** [comment]
Chip! How cute name it is!:satisfied:
OK~, thanks:thumbsup:
