### ISSUE TITLE
UI Design

### ISSUE THREAD

**Issue by lilycoco** [rokumura7/penguinhouse_front#8]
You can use any UI design tools like Adobe XD and Figma, or just code a simple mockup

**Comment by rokumura7** [comment]
https://www.figma.com/file/gTRAjUuhCzmefQfC6QJwkY/Untitled?node-id=3%3A1

**Comment by rokumura7** [comment]
メイン：#6973A2
サブ：#58B3E2
アクセント：#BFE8AE
